name: Continuous Integration

on:
  push:
    branches: [2.x]
  pull_request:
    branches: [2.x]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Lint
        run: flake8 . --statistics --doctests --exclude=acapi2/tests,./build

      - name: Typehints
        run: mypy acapi2 --ignore-missing-imports

      - name: Tests
        run: nosetests --with-coverage --cover-package=acapi2

      - name: Codecov Report
        uses: codecov/codecov-action@v2
